# Generated by Django 5.1.15 on 2026-06-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursecontent_file_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pertanyaan')),
                ('weight', models.PositiveIntegerField(default=10, verbose_name='Bobot Nilai')),
            ],
            options={
                'verbose_name': 'Pertanyaan',
                'verbose_name_plural': 'Pertanyaan',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pilihan')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Benar?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='Pertanyaan')),
            ],
            options={
                'verbose_name': 'Pilihan Jawaban',
                'verbose_name_plural': 'Pilihan Jawaban',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Kuis')),
                ('description', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('passing_grade', models.IntegerField(default=70, verbose_name='Batas Kelulusan')),
                ('attempt_limit', models.PositiveIntegerField(default=3, verbose_name='Batas Percobaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Kursus')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursecontent', verbose_name='Materi/Lesson')),
            ],
            options={
                'verbose_name': 'Kuis',
                'verbose_name_plural': 'Kuis',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Kuis'),
        ),
    ]
